:title: Further reading
:body: |
  
  To learn more about Bonsai, you can check the [source of this site](http://github.com/benschwarz/bonsai-site) or read the [google group](http://groups.google.com/). If you find something that you feel isn't quite right - [post an issue](http://github.com/benschwarz/bonsai/issues) for discussion.